{% set name = "dbf" %}
{% set version = "0.99.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5002bb7a579a5302d3db63738efe3e9d2532ea54a6f630176d3526416ffe00a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aenum

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - dbf
  commands:
    - pip check

about:
  home: https://pypi.python.org/pypi/dbf
  license: BSD-3-Clause
  license_family: BSD
  license_file: dbf/LICENSE
  summary: Pure python package for reading/writing dBase, FoxPro, and Visual FoxPro .dbf files (including memos)

  description: |
    Dbf is a pure Python package for reading/writing dBase, FoxPro, and
    Visual FoxPro .dbf files. Currently supports dBase III, Clipper, FoxPro,
    and Visual FoxPro tables. Text is returned as unicode, and codepage settings
    in tables are honored.
  doc_url: http://pythonhosted.org/dbf/
  dev_url: https://github.com/ethanfurman/dbf

extra:
  recipe-maintainers:
    - synapticarbors
