{% set name = "dbf" %}
{% set version = "0.97.3" %}
{% set sha256 = "9ad42697b6da1034e12a1c6ceb9fc0267e6ea5c562cc675145e3c2bb050e1d95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - aenum

test:
  imports:
    - dbf

about:
  home: https://pypi.python.org/pypi/dbf
  license: BSD 3-clause
  license_family: BSD
  summary: 'Pure python package for reading/writing dBase, FoxPro, and Visual FoxPro .dbf files (including memos)'

  description: |
    Dbf is a pure Python package for reading/writing dBase, FoxPro, and
    Visual FoxPro .dbf files. Currently supports dBase III, Clipper, FoxPro,
    and Visual FoxPro tables. Text is returned as unicode, and codepage settings
    in tables are honored.
  doc_url: http://pythonhosted.org/dbf/
  dev_url: https://bitbucket.org/stoneleaf/dbf

extra:
  recipe-maintainers:
    - synapticarbors
